INSERT INTO user_role (role) VALUES ('ADMIN'),('USER'),('GUEST');
INSERT INTO application_status (status) VALUES ('ACCEPT'),('PROCESS'),('DECLINE');
INSERT INTO faculty (name, number_of_student, short_name) VALUES ('Aerospace system faculty',20,'ASSF');
INSERT INTO faculty (name, number_of_student, short_name) VALUES ('Information technology Faculty',20,'ITF');
INSERT INTO faculty (name, number_of_student, short_name) VALUES ('Applied System Analysis',20,'ASA');
INSERT INTO user (name,sex,birth,phone,address,email,password,user_role_id) VALUES ('Yarema','M','1992-12-12','5678','Kyiv','yaremenko.taras@gmail.com',1111,1);
INSERT INTO user (name,sex,birth,phone,address,email,password,user_role_id) VALUES ('Yarema','M','1992-12-12','5678','Kyiv','yaremenko.taras@gmail.ru',1111,2);
INSERT INTO user (name,sex,birth,phone,address,email,password,user_role_id) VALUES ('Zdolbunovskiy Vitaliy','M','1997-12-12','5678','Kyiv','aaaa@qqq',1111,2);
INSERT INTO user (name,sex,birth,phone,address,email,password,user_role_id) VALUES ('Opanasenko Evgeniy','M','1996-4-4','5678','Kyiv','bbbb@qqq',1111,2);
INSERT INTO user (name,sex,birth,phone,address,email,password,user_role_id) VALUES ('Teslya Yaroslav','M','1996-6-17','5678','Lviv','cccc@qqq',1111,2);
INSERT INTO user (name,sex,birth,phone,address,email,password,user_role_id) VALUES ('Chopok Viktoria','F','1997-11-27','5678','Kharkiv','dddd@qqq',1111,2);
INSERT INTO subject (name) VALUES ('Mathematic'), ('Physics'), ('Language'), ('History');
INSERT INTO faculty_subject (faculty_id,subject_id,min_mark)VALUES (1,1,140);
INSERT INTO faculty_subject (faculty_id,subject_id,min_mark)VALUES (1,2,140);
INSERT INTO faculty_subject (faculty_id,subject_id,min_mark)VALUES (1,3,140);
INSERT INTO faculty_subject (faculty_id,subject_id,min_mark)VALUES (2,1,150);
INSERT INTO faculty_subject (faculty_id,subject_id,min_mark)VALUES (2,2,150);
INSERT INTO faculty_subject (faculty_id,subject_id,min_mark)VALUES (2,3,150);
INSERT INTO faculty_subject (faculty_id,subject_id,min_mark)VALUES (3,1,160);
INSERT INTO faculty_subject (faculty_id,subject_id,min_mark)VALUES (3,2,160);
INSERT INTO faculty_subject (faculty_id,subject_id,min_mark)VALUES (3,3,160);
INSERT INTO faculty_subject (faculty_id,subject_id,min_mark)VALUES (3,4,160);
INSERT INTO applicant_mark (mark,user_id,subject_id) VALUES (170,1,1);
INSERT INTO applicant_mark (mark,user_id,subject_id) VALUES (169,1,2);
INSERT INTO applicant_mark (mark,user_id,subject_id) VALUES (175,1,3);
INSERT INTO applicant_mark (mark,user_id,subject_id) VALUES (160,1,4);
INSERT INTO applicant_mark (mark,user_id,subject_id) VALUES (175,2,1);
INSERT INTO applicant_mark (mark,user_id,subject_id) VALUES (177,2,2);
INSERT INTO applicant_mark (mark,user_id,subject_id) VALUES (180,2,3);
INSERT INTO applicant_mark (mark,user_id,subject_id) VALUES (164,2,4);
INSERT INTO applicant_mark (mark,user_id,subject_id) VALUES (172,3,1);
INSERT INTO applicant_mark (mark,user_id,subject_id) VALUES (180,3,2);
INSERT INTO applicant_mark (mark,user_id,subject_id) VALUES (179,3,3);
INSERT INTO applicant_mark (mark,user_id,subject_id) VALUES (181,3,4);
INSERT INTO applicant_mark (mark,user_id,subject_id) VALUES (186,4,1);
INSERT INTO applicant_mark (mark,user_id,subject_id) VALUES (188,4,2);
INSERT INTO applicant_mark (mark,user_id,subject_id) VALUES (182,4,3);
INSERT INTO applicant_mark (mark,user_id,subject_id) VALUES (190,4,4);
INSERT INTO application (date, description, overall, faculty_id, user_id, application_status_id) VALUES   ('2017-01-01','KPI',480,1,1,2);
INSERT INTO application (date, description, overall, faculty_id, user_id, application_status_id) VALUES   ('2017-01-01','KPI',500,2,1,2);
INSERT INTO application (date, description, overall, faculty_id, user_id, application_status_id) VALUES   ('2017-01-01','KPI',470,3,1,2);
INSERT INTO application (date, description, overall, faculty_id, user_id, application_status_id) VALUES   ('2017-01-01','KPI',500,1,2,2);
INSERT INTO application (date, description, overall, faculty_id, user_id, application_status_id) VALUES   ('2017-01-01','KPI',510,2,2,2);
INSERT INTO application (date, description, overall, faculty_id, user_id, application_status_id) VALUES   ('2017-01-01','KPI',490,3,2,2);
INSERT INTO application (date, description, overall, faculty_id, user_id, application_status_id) VALUES   ('2017-01-01','KPI',520,1,3,2);
INSERT INTO application (date, description, overall, faculty_id, user_id, application_status_id) VALUES   ('2017-01-01','KPI',540,2,3,2);
INSERT INTO application (date, description, overall, faculty_id, user_id, application_status_id) VALUES   ('2017-01-01','KPI',510,3,3,2);
INSERT INTO application (date, description, overall, faculty_id, user_id, application_status_id) VALUES   ('2017-01-01','KPI',530,1,4,2);
INSERT INTO application (date, description, overall, faculty_id, user_id, application_status_id) VALUES   ('2017-01-01','KPI',540,2,4,2);
INSERT INTO application (date, description, overall, faculty_id, user_id, application_status_id) VALUES   ('2017-01-01','KPI',510,3,4,2);